stages:
  - client
  - build

variables:
  IMAGE_NAME: testerca11/app
  IMAGE_TAG: VueJS-app-1.0

client_build:
  stage: client
  tags:
    - docker
  image: node:21-alpine3.18
  allow_failure: true
  before_script:
    - cd client
  script:
    - npm install
    #- npm run build

build_script:
  stage: build
  tags:
    - docker
  image: docker:25.0.0-beta.2-cli
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cd server
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t $IMAGE_NAME:IMAGE_TAG .
    - docker push $IMAGE_NAME:IMAGE_TAG