stages:
  - test
  
docker_test:
  image: tmainer/docker-compose
  services: 
    - docker:dbind
  stage: test
  before_script:
    - docker-compose build --no-cache
  script:
    docker build -t frontend ./client
    docker build -t backend ./server
