stages:
  - lint_client
  - lint_server
  - client
  - server
  - server_start
  - performance_test

eslint_client:
  stage: lint_client
  tags:
    - docker
  image: node:lts-bullseye-slim
  allow_failure: true
  before_script:
    - cd client
  script:
    - npm install
    - npm run lint

eslint_server:
  stage: lint_server
  tags:
    - docker
  image: node:lts-bullseye-slim
  allow_failure: true
  before_script:
    - cd server
  script:
    - npm install
    - npm run lint

frontend:
  stage: client
  tags:
    - kaniko
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  variables:
    IMAGE_TAG: latest
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "$CI_PROJECT_DIR/client" --dockerfile "$CI_PROJECT_DIR/client/Dockerfile" --destination "$CI_REGISTRY_IMAGE:client"

backend:
  stage: server
  tags:
    - kaniko
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  variables:
    IMAGE_TAG: latest
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "$CI_PROJECT_DIR/server" --dockerfile "$CI_PROJECT_DIR/server/Dockerfile" --destination "$CI_REGISTRY_IMAGE:server"
  needs: [ "frontend" ]

server:
  stage: server_start
  allow_failure: true
  before_script:
    - cd server
  script:
    - npm install
    - npm start ./server.js

performance_test:
  stage: performance_test
  tags:
    - docker
  image: node:lts-bullseye-slim
  script:
    - npm install -g artillery
    - artillery run ./performance-test-config.yml
  needs: [ "server" ]



