version: '3.1'


services:
  db:
    image: mariadb:lts
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER_FILE: /run/secrets/rootUser
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/rootPass
      MYSQL_USER_FILE: /run/secrets/user
      MYSQL_PASSWORD_FILE: /run/secrets/pass
      MYSQL_DATABASE: webappdb
    secrets:
      - rootUser
      - rootPass
      - user
      - pass
    volumes:
      - db_data:/var/lib/mysql:Z
    ports:
      - "3306:3306"
    networks:
      - intern

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: "http://proxy:8000/pma/"
    networks:
      - intern

  frontend:
    build:
      context: ./client
    networks:
      - intern

  backend:
    build:
      context: ./server
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: webappdb
      DB_PASSWORD_FILE: run/secrets/pass
      DB_USER_FILE: run/secrets/user
      FRONTEND_HOST: frontend
      FRONTEND_PORT: 8000
    secrets:
      - user
      - pass
    networks:
      - intern

  proxy:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - db
    networks:
      - intern

secrets:
  rootUser:
    file: ./secrets/rootUser.txt
  rootPass:
    file: ./secrets/rootPass.txt
  user:
    file: ./secrets/user.txt
  pass:
    file: ./secrets/pass.txt


networks:
  intern:
    driver: bridge


volumes:
  db_data: