version: '3.1'


services:
  db:
    image: mariadb:11.2
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER_FILE: /run/secrets/rootUser
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/rootPass
      MYSQL_USER_FILE: /run/secrets/user
      MYSQL_PASSWORD_FILE: /run/secrets/pass
      MYSQL_DATABASE: webappdb
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 20
    secrets:
      - rootUser
      - rootPass
      - user
      - pass
    volumes:
      - db_data:/var/lib/mysql:Z
      - ./init.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - intern

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: "http://proxy:8000/pma/"
    networks:
      - intern

  frontend:
    build:
      context: ./client
    networks:
      - intern

  backend:
    build:
      context: ./server
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: webappdb
      DB_PASSWORD_FILE: run/secrets/pass
      DB_USER_FILE: run/secrets/user
      FRONTEND_HOST: frontend
      FRONTEND_PORT: 8000
    secrets:
      - user
      - pass
    networks:
      - intern

  proxy:
    image: nginx:1.25.3-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - db
    networks:
      - intern

secrets:
  rootUser:
    file: ./secrets/rootUser.txt
  rootPass:
    file: ./secrets/rootPass.txt
  user:
    file: ./secrets/user.txt
  pass:
    file: ./secrets/pass.txt


networks:
  intern:
    driver: bridge


volumes:
  db_data: